wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13+
    start_time: 1655112567
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.9.13+
      5: 0.12.17
      8:
      - 5
aa:
  desc: null
  value: rand-m9-mstd0.5-inc1
amp:
  desc: null
  value: false
apex_amp:
  desc: null
  value: false
aug_splits:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 64
checkpoint_hist:
  desc: null
  value: 20
clip_grad:
  desc: null
  value: null
clip_mode:
  desc: null
  value: norm
color_jitter:
  desc: null
  value: 0.4
cooldown_epochs:
  desc: null
  value: 0
cutmix:
  desc: null
  value: 0.0
cutmix_minmax:
  desc: null
  value: null
data_dir:
  desc: null
  value: /NOT/WORKING
dataset:
  desc: null
  value: ''
dataset_size:
  desc: null
  value: 1281167
decay_epochs:
  desc: null
  value: 30
decay_rate:
  desc: null
  value: 0.1
distributed:
  desc: null
  value: true
drop:
  desc: null
  value: 0.0
drop_block:
  desc: null
  value: null
drop_connect:
  desc: null
  value: null
drop_path:
  desc: null
  value: 0.1
entity_name:
  desc: null
  value: daweek
epoch_repeats:
  desc: null
  value: 0.0
epochs:
  desc: null
  value: 300
eval_metric:
  desc: null
  value: loss
experiment:
  desc: null
  value: pretrain_deit_tiny_imnet1k_lr6.0e-4_epochs300_bs131072_cpu2048
group_name:
  desc: null
  value: pretrain
hflip:
  desc: null
  value: 0.0
img_size:
  desc: null
  value: null
input_size:
  desc: null
  value: null
interpolation:
  desc: null
  value: bicubic
interval_saved_epochs:
  desc: null
  value: 5
jsd:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
log_interval:
  desc: null
  value: 50
log_wandb:
  desc: null
  value: true
lr:
  desc: null
  value: 0.0006
lr_cycle_limit:
  desc: null
  value: 1
lr_cycle_mul:
  desc: null
  value: 1.0
lr_noise:
  desc: null
  value: null
lr_noise_pct:
  desc: null
  value: 0.67
lr_noise_std:
  desc: null
  value: 1.0
mean:
  desc: null
  value: null
min_lr:
  desc: null
  value: 1.0e-05
mixup:
  desc: null
  value: 0.0
mixup_mode:
  desc: null
  value: batch
mixup_off_epoch:
  desc: null
  value: 0
mixup_prob:
  desc: null
  value: 1.0
mixup_switch_prob:
  desc: null
  value: 0.5
model:
  desc: null
  value: vit_deit_tiny_patch16_224
momentum:
  desc: null
  value: 0.9
native_amp:
  desc: null
  value: false
no_aug:
  desc: null
  value: false
no_prefetcher:
  desc: null
  value: true
no_resume_opt:
  desc: null
  value: false
num_classes:
  desc: null
  value: 1000
opt:
  desc: null
  value: adamw
opt_betas:
  desc: null
  value: null
opt_eps:
  desc: null
  value: null
output:
  desc: null
  value: /home/hp190122/u01961/working/deepL/transformer/timm_main_sora/checkpoint/tiny/imnet1k/pre_training
patience_epochs:
  desc: null
  value: 10
pin_mem:
  desc: null
  value: false
prefetcher:
  desc: null
  value: false
pretrained:
  desc: null
  value: false
project_name:
  desc: null
  value: fugaku
rank:
  desc: null
  value: 0
ratio:
  desc: null
  value:
  - 0.75
  - 1.3333333333333333
recount:
  desc: null
  value: 1
recovery_interval:
  desc: null
  value: 0
remode:
  desc: null
  value: pixel
repeated_aug:
  desc: null
  value: true
reprob:
  desc: null
  value: 0.25
resplit:
  desc: null
  value: false
resume:
  desc: null
  value: ''
save_images:
  desc: null
  value: false
scale:
  desc: null
  value:
  - 0.08
  - 1.0
sched:
  desc: null
  value: cosine_iter
seed:
  desc: null
  value: 42
smoothing:
  desc: null
  value: 0.1
start_epoch:
  desc: null
  value: null
std:
  desc: null
  value: null
train_interpolation:
  desc: null
  value: random
train_split:
  desc: null
  value: train
trainshards:
  desc: null
  value: /home/hp190122/u01961/data/ILSVRC2012_5MB_shards/train/imagenet-train-{000000..028606}.tar
val_split:
  desc: null
  value: validation
vflip:
  desc: null
  value: 0.0
warmup_epochs:
  desc: null
  value: 5
warmup_iter:
  desc: null
  value: 0
warmup_lr:
  desc: null
  value: 0.0001
webdataset:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.05
workers:
  desc: null
  value: 1
world_size:
  desc: null
  value: 2048
